name: Deploy web app to Azure Static Web Apps

on:
  push:
    branches: ['main']

jobs:
  build_and_deploy_job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Debugging Step - Check if secret is available
        run: echo "Secret: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}"  # Prints the secret (only for debugging, DO NOT use in production)

      - name: Deploy to Azure Static Web Apps
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}  # for PR comments (optional)
          action: 'upload'
          app_location: "/"  # Root location of your app code
          app_artifact_location: "build"  # Location of the build output
